import java.io.*;

public class Entrada {


    public static void main(String[] args) {

        Errores errores = new Errores();


            errores.lecturaFichero();


        /*String palabra = null;
        int[] numeros = new int[]{1,2,3,4,5,6,7,8,9,10};

        try{
            System.out.println(palabra.length());
            System.out.println(numeros[11]);
            // cierre de fichero
        } catch (NullPointerException e){
            System.out.println("Encontrado un fallo de nulo");
            //System.out.println(e.getMessage());
        } catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Encontrado un fallo de array");
            //System.out.println(e.getMessage());
        } finally {
            System.out.println("Ejecutado de forma obligatoria en try/catch");
        }


        System.out.println("Ejecucion fuera del try/catch");*/
    }
}
